"""empty message

Revision ID: 5a291b1d134b
Revises: f178fe27f43b
Create Date: 2025-03-13 11:04:24.395580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a291b1d134b'
down_revision: Union[str, None] = 'f178fe27f43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_tv', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_tv')
    # ### end Alembic commands ###
