"""empty message

Revision ID: 8d57f4315d4d
Revises: 5a291b1d134b
Create Date: 2025-03-19 12:42:54.507338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d57f4315d4d'
down_revision: Union[str, None] = '5a291b1d134b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('count_of_people', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'count_of_people')
    # ### end Alembic commands ###
