"""empty message

Revision ID: 9d72cbf1260f
Revises: 441cb3237759
Create Date: 2025-02-19 16:36:53.757498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d72cbf1260f"
down_revision: Union[str, None] = "441cb3237759"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reservation", sa.Column("start_date", sa.Date(), nullable=False))
    op.add_column("reservation", sa.Column("end_date", sa.Date(), nullable=False))
    op.drop_column("reservation", "departure_date")
    op.drop_column("reservation", "check_in_date")
    op.alter_column(
        "rooms",
        "rating",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "rooms",
        "rating",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.add_column(
        "reservation",
        sa.Column("check_in_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "reservation",
        sa.Column("departure_date", sa.DATE(), autoincrement=False, nullable=False),
    )
    op.drop_column("reservation", "end_date")
    op.drop_column("reservation", "start_date")
    # ### end Alembic commands ###
