"""empty message

Revision ID: a03e65fb8470
Revises: b900bb72c6ef
Create Date: 2025-02-19 17:04:40.723537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a03e65fb8470'
down_revision: Union[str, None] = 'b900bb72c6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('count_nights', sa.Integer(), nullable=False))
    op.drop_column('reservation', 'count_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('count_days', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('reservation', 'count_nights')
    # ### end Alembic commands ###
