"""empty message

Revision ID: af6a4cfe429d
Revises: aadb031eeaa1
Create Date: 2025-03-13 10:46:26.256131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6a4cfe429d'
down_revision: Union[str, None] = 'aadb031eeaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_noisecancelling', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('is_wifi', sa.Boolean(), nullable=True))
    op.add_column('rooms', sa.Column('is_pc', sa.Boolean(), nullable=True))
    op.drop_column('rooms', 'is_conditioning')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_conditioning', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'is_pc')
    op.drop_column('rooms', 'is_wifi')
    op.drop_column('rooms', 'is_noisecancelling')
    # ### end Alembic commands ###
