"""empty message

Revision ID: eb9f967791ce
Revises: 67251a933f92
Create Date: 2025-02-22 12:53:10.724542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb9f967791ce'
down_revision: Union[str, None] = '67251a933f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('surname', sa.String(), nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=False))
    op.add_column('users', sa.Column('time_zone', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'time_zone')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
