"""empty message

Revision ID: f01e3ae17caf
Revises: 469c0bd4a599
Create Date: 2025-02-21 23:07:53.843759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01e3ae17caf'
down_revision: Union[str, None] = '469c0bd4a599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_conditioning', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_conditioning')
    # ### end Alembic commands ###
